package adsbdb

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"time"

	"github.com/hashicorp/golang-lru/v2/expirable"
)

const (
	callsignApiPath = `https://api.adsbdb.com/v0/callsign/`
	aircraftApiPath = `https://api.adsbdb.com/v0/aircraft/`
)

type AutoGenerated struct {
	Response struct {
		Flightroute struct {
			Callsign     string `json:"callsign"`
			CallsignIcao string `json:"callsign_icao"`
			CallsignIata string `json:"callsign_iata"`
			Airline      struct {
				Name       string `json:"name"`
				Icao       string `json:"icao"`
				Iata       string `json:"iata"`
				Country    string `json:"country"`
				CountryIso string `json:"country_iso"`
				Callsign   string `json:"callsign"`
			} `json:"airline"`
			Origin struct {
				CountryIsoName string  `json:"country_iso_name"`
				CountryName    string  `json:"country_name"`
				Elevation      int     `json:"elevation"`
				IataCode       string  `json:"iata_code"`
				IcaoCode       string  `json:"icao_code"`
				Latitude       float64 `json:"latitude"`
				Longitude      float64 `json:"longitude"`
				Municipality   string  `json:"municipality"`
				Name           string  `json:"name"`
			} `json:"origin"`
			Destination struct {
				CountryIsoName string  `json:"country_iso_name"`
				CountryName    string  `json:"country_name"`
				Elevation      int     `json:"elevation"`
				IataCode       string  `json:"iata_code"`
				IcaoCode       string  `json:"icao_code"`
				Latitude       float64 `json:"latitude"`
				Longitude      float64 `json:"longitude"`
				Municipality   string  `json:"municipality"`
				Name           string  `json:"name"`
			} `json:"destination"`
		} `json:"flightroute"`
	} `json:"response"`
}

type AircraftAPIResponse struct {
	Response struct {
		Aircraft struct {
			Type                            string `json:"type"`
			IcaoType                        string `json:"icao_type"`
			Manufacturer                    string `json:"manufacturer"`
			ModeS                           string `json:"mode_s"`
			Registration                    string `json:"registration"`
			RegisteredOwnerCountryIsoName   string `json:"registered_owner_country_iso_name"`
			RegisteredOwnerCountryName      string `json:"registered_owner_country_name"`
			RegisteredOwnerOperatorFlagCode string `json:"registered_owner_operator_flag_code"`
			RegisteredOwner                 string `json:"registered_owner"`
			URLPhoto                        string `json:"url_photo"`
			URLPhotoThumbnail               string `json:"url_photo_thumbnail"`
		} `json:"aircraft"`
	} `json:"response"`
}

type Adsbdb struct {
	callsignCache *expirable.LRU[string, *AutoGenerated]
	aircraftCache *expirable.LRU[string, *AircraftAPIResponse]
}

func NewAdsbdb() *Adsbdb {
	callsignCache := expirable.NewLRU[string, *AutoGenerated](1000, nil, time.Hour*24)
	aircraftCache := expirable.NewLRU[string, *AircraftAPIResponse](1000, nil, time.Hour*24)

	return &Adsbdb{
		callsignCache: callsignCache,
		aircraftCache: aircraftCache,
	}
}

func (a *Adsbdb) GetCallsign(code string) (*AutoGenerated, error) {
	if code == "" {
		return nil, errors.New("callsign code cannot be empty")
	}

	if cached, ok := a.callsignCache.Get(code); ok {
		return cached, nil
	}

	req, err := http.NewRequest("GET", strings.TrimSpace(callsignApiPath+code), nil)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", "application/json")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}

	defer func() { _ = res.Body.Close() }()

	if res.StatusCode != http.StatusOK {
		return nil, errors.New(res.Status)
	}

	dec := json.NewDecoder(res.Body)

	du := &AutoGenerated{}
	err = dec.Decode(du)

	if err != nil {
		return nil, err
	}
	a.callsignCache.Add(code, du)
	return du, nil
}

func (a *Adsbdb) GetRegistration(hex string) (*AircraftAPIResponse, error) {
	if hex == "" {
		return nil, errors.New("hex code cannot be empty")
	}

	if cached, ok := a.aircraftCache.Get(hex); ok {
		return cached, nil
	}

	req, err := http.NewRequest("GET", strings.TrimSpace(aircraftApiPath+hex), nil)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", "application/json")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}

	defer func() { _ = res.Body.Close() }()

	if res.StatusCode != http.StatusOK {
		return nil, errors.New(res.Status)
	}

	dec := json.NewDecoder(res.Body)

	du := &AircraftAPIResponse{}
	err = dec.Decode(du)
	if err != nil {
		return nil, err
	}
	a.aircraftCache.Add(hex, du)
	return du, nil
}
