package adsbdb

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

type Airport struct {
	Code           string  `json:"code"`
	CodeIcao       string  `json:"code_icao"`
	CodeIata       string  `json:"code_iata"`
	CodeLid        *string `json:"code_lid"`
	Timezone       string  `json:"timezone"`
	Name           string  `json:"name"`
	City           string  `json:"city"`
	AirportInfoUrl string  `json:"airport_info_url"`
}

type FlightAwareFlight struct {
	Ident                         string   `json:"ident"`
	IdentIcao                     string   `json:"ident_icao"`
	IdentIata                     string   `json:"ident_iata"`
	ActualRunwayOff               string   `json:"actual_runway_off"`
	ActualRunwayOn                string   `json:"actual_runway_on"`
	FaFlightId                    string   `json:"fa_flight_id"`
	Operator                      string   `json:"operator"`
	OperatorIcao                  string   `json:"operator_icao"`
	OperatorIata                  string   `json:"operator_iata"`
	FlightNumber                  string   `json:"flight_number"`
	Registration                  string   `json:"registration"`
	AtcIdent                      *string  `json:"atc_ident"`
	InboundFaFlightId             string   `json:"inbound_fa_flight_id"`
	Codeshares                    []string `json:"codeshares"`
	CodesharesIata                []string `json:"codeshares_iata"`
	Blocked                       bool     `json:"blocked"`
	Diverted                      bool     `json:"diverted"`
	Cancelled                     bool     `json:"cancelled"`
	PositionOnly                  bool     `json:"position_only"`
	Origin                        Airport  `json:"origin"`
	Destination                   Airport  `json:"destination"`
	DepartureDelay                int      `json:"departure_delay"`
	ArrivalDelay                  int      `json:"arrival_delay"`
	FiledEte                      int      `json:"filed_ete"`
	ForesightPredictionsAvailable bool     `json:"foresight_predictions_available"`
	ScheduledOut                  string   `json:"scheduled_out"`
	EstimatedOut                  string   `json:"estimated_out"`
	ActualOut                     string   `json:"actual_out"`
	ScheduledOff                  string   `json:"scheduled_off"`
	EstimatedOff                  string   `json:"estimated_off"`
	ActualOff                     string   `json:"actual_off"`
	ScheduledOn                   string   `json:"scheduled_on"`
	EstimatedOn                   string   `json:"estimated_on"`
	ActualOn                      string   `json:"actual_on"`
	ScheduledIn                   string   `json:"scheduled_in"`
	EstimatedIn                   string   `json:"estimated_in"`
	ActualIn                      string   `json:"actual_in"`
	ProgressPercent               int      `json:"progress_percent"`
	Status                        string   `json:"status"`
	AircraftType                  string   `json:"aircraft_type"`
	RouteDistance                 int      `json:"route_distance"`
	FiledAirspeed                 int      `json:"filed_airspeed"`
	FiledAltitude                 int      `json:"filed_altitude"`
	Route                         string   `json:"route"`
	BaggageClaim                  *string  `json:"baggage_claim"`
	SeatsCabinBusiness            *int     `json:"seats_cabin_business"`
	SeatsCabinCoach               *int     `json:"seats_cabin_coach"`
	SeatsCabinFirst               *int     `json:"seats_cabin_first"`
	GateOrigin                    string   `json:"gate_origin"`
	GateDestination               string   `json:"gate_destination"`
	TerminalOrigin                string   `json:"terminal_origin"`
	TerminalDestination           *string  `json:"terminal_destination"`
	Type                          string   `json:"type"`
}

type FlightAwareResponse struct {
	Flights []FlightAwareFlight `json:"flights"`
}

func (a *Adsbdb) GetEnRouteFlight(flightIdent string) (*AutoGenerated, error) {
	if flightIdent == "" {
		return nil, errors.New("flightIdent cannot be empty")
	}

	du := &FlightAwareResponse{}
	if err := a.Load("enroute_flight", flightIdent, 0, du); err == nil {
		return a.faResponseToAutoGenerated(du)
	}

	start := time.Now().Format("2006-01-02")
	url := "https://aeroapi.flightaware.com/aeroapi/flights/" + flightIdent +
		"?ident_type=designator&start=" + start

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Add("Accept", "application/json; charset=UTF-8")
	req.Header.Add("x-apikey", a.flightAwareApiKey)

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()

	if res.StatusCode != http.StatusOK {
		fmt.Printf("Error: %s (%s)\n", res.Status, url)
		body, _ := io.ReadAll(res.Body)
		fmt.Println("Response body:", string(body))
		return nil, errors.New(res.Status)
	}

	if err := json.NewDecoder(res.Body).Decode(&du); err != nil {
		return nil, err
	}

	_ = a.Save("enroute_flight", flightIdent, du)
	return a.faResponseToAutoGenerated(du)
}

func (a *Adsbdb) faResponseToAutoGenerated(faResp *FlightAwareResponse) (*AutoGenerated, error) {
	for _, flight := range faResp.Flights {
		if strings.Contains(flight.Status, "En Route") {
			// Map to your AutoGenerated struct
			ag := &AutoGenerated{}
			ag.Response.Flightroute.Callsign = flight.Ident
			ag.Response.Flightroute.Origin.Name = flight.Origin.Name
			ag.Response.Flightroute.Origin.IcaoCode = flight.Origin.CodeIcao
			ag.Response.Flightroute.Origin.IataCode = flight.Origin.CodeIata
			ag.Response.Flightroute.Origin.Municipality = flight.Origin.City
			ag.Response.Flightroute.Origin.CountryIsoName = flight.Origin.Timezone // Not exact, but for demo
			ag.Response.Flightroute.Destination.Name = flight.Destination.Name
			ag.Response.Flightroute.Destination.IcaoCode = flight.Destination.CodeIcao
			ag.Response.Flightroute.Destination.IataCode = flight.Destination.CodeIata
			ag.Response.Flightroute.Destination.Municipality = flight.Destination.City
			ag.Response.Flightroute.Destination.CountryIsoName = flight.Destination.Timezone // Not exact, but for demo
			return ag, nil
		}
	}

	return nil, errors.New("no en route flight found")
}
